redis:
    host: "127.0.0.1"
    port: 6379
    db: 1 #asynq用的是db+1
    user: root
    pass: "061004"

mysql:
    host: "127.0.0.1"
    port: 3306
    database: "chaoxing"
    username: "root"
    password: "password"
    charset: "utf8mb4"
    max_idle_conns: 10
    max_open_conns: 100

jwt:
    secret_key: "chaoxing_secret_key"
    expire_time: 24 # 过期时间(小时)
